spring:
    application:
        name: gulimall-auth-server
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
    redis:
        host: 192.168.56.111
        port: 6379
    session:
        store-type: redis
server:
    port: 20000